# Generated by Django 3.2.10 on 2023-03-13 10:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0002_alter_account_login'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': 'Аккаунт', 'verbose_name_plural': 'Аккануты'},
        ),
        migrations.AlterField(
            model_name='account',
            name='can_create',
            field=models.BooleanField(default=False, verbose_name='Возможность создавать тесты'),
        ),
        migrations.AlterField(
            model_name='account',
            name='first_name',
            field=models.CharField(max_length=70, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='account',
            name='last_name',
            field=models.CharField(max_length=70, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='account',
            name='login',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Войти'),
        ),
    ]
