# Generated by Django 3.2.10 on 2023-03-11 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_answer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('npp',), 'verbose_name': 'категория', 'verbose_name_plural': 'категории'},
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ('npp',), 'verbose_name': 'тест', 'verbose_name_plural': 'тесты'},
        ),
    ]
