# Generated by Django 3.2.10 on 2023-03-13 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20230313_1518'),
        ('quiz', '0005_auto_20230311_1729'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'Ответ к вопросу', 'verbose_name_plural': 'Ответы к вопросам'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('npp',), 'verbose_name': 'Рубрика', 'verbose_name_plural': 'Рубрики'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Вопрос виктоины', 'verbose_name_plural': 'Вопросы викторин'},
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ('npp',), 'verbose_name': 'Викторина', 'verbose_name_plural': 'Викторины'},
        ),
        migrations.RemoveField(
            model_name='answer',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.RemoveField(
            model_name='question',
            name='image',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='description',
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.CharField(max_length=512, verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='is_correct',
            field=models.BooleanField(default=False, verbose_name='Правильный'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.question', verbose_name='Выбор вопроса'),
        ),
        migrations.AlterField(
            model_name='category',
            name='npp',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Сортировка'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=512, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='question',
            name='full_text',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(max_length=512, verbose_name='Текст вопроса'),
        ),
        migrations.AlterField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz', verbose_name='Викторина'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.account', verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='Отображение'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Изменен'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='npp',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Сортировка'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='title',
            field=models.CharField(max_length=512, verbose_name='Название'),
        ),
    ]
