# Generated by Django 3.2.10 on 2023-03-25 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_auto_20230320_2144'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('id',), 'verbose_name': 'Рубрика', 'verbose_name_plural': 'Рубрики'},
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ('id',), 'verbose_name': 'Викторина', 'verbose_name_plural': 'Викторины'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='npp',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='npp',
        ),
    ]
